/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AzkarRouteImport } from './routes/azkar'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasbihRouteImport } from './routes/tasbih'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarRoute = AzkarRouteImport.update({
  id: '/azkar',
  path: '/azkar',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/azkar': typeof AzkarRoute
  '/community': typeof CommunityRoute
  '/hadith': typeof HadithRoute
  '/prayer': typeof PrayerRoute
  '/quran': typeof QuranRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/tasbih': typeof TasbihRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/azkar': typeof AzkarRoute
  '/community': typeof CommunityRoute
  '/hadith': typeof HadithRoute
  '/prayer': typeof PrayerRoute
  '/quran': typeof QuranRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/tasbih': typeof TasbihRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/azkar': typeof AzkarRoute
  '/community': typeof CommunityRoute
  '/hadith': typeof HadithRoute
  '/prayer': typeof PrayerRoute
  '/quran': typeof QuranRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/tasbih': typeof TasbihRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/azkar'
    | '/community'
    | '/hadith'
    | '/prayer'
    | '/quran'
    | '/saved'
    | '/settings'
    | '/tasbih'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/azkar'
    | '/community'
    | '/hadith'
    | '/prayer'
    | '/quran'
    | '/saved'
    | '/settings'
    | '/tasbih'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/azkar'
    | '/community'
    | '/hadith'
    | '/prayer'
    | '/quran'
    | '/saved'
    | '/settings'
    | '/tasbih'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  AzkarRoute: typeof AzkarRoute
  CommunityRoute: typeof CommunityRoute
  HadithRoute: typeof HadithRoute
  PrayerRoute: typeof PrayerRoute
  QuranRoute: typeof QuranRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  TasbihRoute: typeof TasbihRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar': {
      id: '/azkar'
      path: '/azkar'
      fullPath: '/azkar'
      preLoaderRoute: typeof AzkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  AzkarRoute: AzkarRoute,
  CommunityRoute: CommunityRoute,
  HadithRoute: HadithRoute,
  PrayerRoute: PrayerRoute,
  QuranRoute: QuranRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  TasbihRoute: TasbihRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
